name: CI - Merge Developer Branches

on:
  push:
    branches:
      - "dev-*"

permissions:
  contents: write

jobs:
  merge-to-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge into development
        run: |
          git fetch origin
          git checkout development
          git merge origin/${GITHUB_REF_NAME} --no-ff -m "Auto merge ${GITHUB_REF_NAME} into development"
          git push origin development
